name: Node.js CI

on:
  push:
    branches: [ "main" ]  # 当 main 分支有代码推送时触发
  pull_request:
    branches: [ "main" ]  # 当有 pull request 合并到 main 分支时触发

jobs:
  build:

    runs-on: windows-latest  # 设置运行环境为 Windows（更改自 ubuntu-latest）

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # 设置要测试的 Node.js 版本
        # 查看支持的 Node.js 版本发布计划：https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4  # 检出代码仓库
    - name: Use Node.js ${{ matrix.node-version }}  # 设置 Node.js 版本
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}  # 使用 matrix 中指定的 Node.js 版本
        cache: 'npm'  # 启用 npm 缓存，提升构建速度
    - run: npm ci  # 使用 npm ci 安装依赖
    - run: npm run build --if-present  # 如果项目中有 build 脚本，则执行构建
    - run: npm test  # 运行测试
